### ISSUE TITLE
Update Sponsorship Tiers

### ISSUE THREAD

**Issue by techguydave** [hudson-hybrids/website#37]
Right now the tiers overlap (ex: $0-200, $200-500). The lower tiers should be ending at $X99 (ex: $0-199, $200-499).

**Comment by MatthewATaylor** [comment]
This issue can stay for now. Soon some more pull requests may come in for fixing it (as Git practice).

**Comment by MatthewATaylor** [comment]
I just altered the Git practice instructions, so this issue will be closed.

**Comment by techguydave** [comment]
So should I not have merged the fix from Jack? I didn't realize you were using it for instructions.

**Comment by MatthewATaylor** [comment]
It's fine. I really should have mentioned that somewhere.
